name = "JuliaImagesDocs"
uuid = "0c275f74-ee56-424f-a19e-b5e11953da87"
authors = ["ashwani rathee <ab669522@gmail.com>"]
version = "0.1.0"

[deps]
MultiDocumenter = "87ed4bf0-c935-4a67-83c3-2a03bee4197c"
